# Generated by Django 3.2.3 on 2021-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210529_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_and_pixels',
            name='tfm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph_and_pixels',
            name='tsm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
