# Generated by Django 3.2.3 on 2021-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_verify',
            field=models.ImageField(default=0, upload_to='imagesverify'),
            preserve_default=False,
        ),
    ]
